version: '3.7'
services: 

  app:
    image: callback-bn-api
    environment:
      - NODE_ENV=docker
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_URL=${DB_URL}
      - BASE_URL=${BASE_URL}
    build:
      context: .
      args:
        - PORT:${APP_PORT}
    volumes:
      - ./:/src/app
    container_name: callback-backend
    
    depends_on:
      - db

    ports: 
      - "4000:4000"
    restart: always
    
  db:

    image: postgres:14.1-alpine
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: callback_db
